config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :signups
  get '/home' => 'pages#home'
  get '/about' => 'pages#about'
  get '/contact' => 'signups#new'
  get '/thanks' => 'pages#thanks'
  post 'signups' => 'signups#create'
  

end

app/models/signup.rb
class Signup < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
  def thanks
  end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
     def new
        @signup = Signup.new
    end
    def create
        @signup = Signup.new(signup_params)
        if @signup.save
            redirect_to thanks_url
        else
            render('new')
        end
    end
    
    private
      def signup_params
 params.require(:signup).permit(:firstname,:email)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stories</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width,minimum-scale=1">
<!--      <link rel="stylesheet" href="//cdn.jsdelivr.net/jquery.sidr/2.2.1/stylesheets/jquery.sidr.dark.min.css">-->
  <link href='https://fonts.googleapis.com/css?family=Lato:400,700,300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  
  
</head>
<body>
		<div id="menu">
        <ul>
            <li><%= link_to("Home", home_path)%> </li>
            <li><%= link_to("About", about_path)%> </li>
            <li><%= link_to("Contact", contact_path)%> </li>
           
        </ul>
    </div>
    <div id="right">
        <div id="menubar">
            <div id="button">Menu</div>
        </div>
  	
        
<%= yield %>
   <div class="footer-section">
          <br>
          <h3>A Shutterbug Project</h3>
	</div>    
  </div>
 
  
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
   
</body>
</html>

app/views/pages/about.html.erb
<div class="about-first-section">
    <h1>Relive your Favorite Memories</h1>
	</div>
<div class="about-second-section">
	<h1>
    No more sorting through photos
  </h1>
  <br>
  <p>
    Stories automatically finds your best photos and creates a new travelogue. This way you can capture and share your special moments in fresh new ways.
  </p>
  <br>
  <br>
   <a href="www.corriere.it" class="btn-main">Sign Up</a>
</div>

app/views/pages/home.html.erb
        <div class="main">
          <br>
          <h1>Create and Share Stories</h1>
          <br>
          <br>
             <%= link_to("Learn More", about_path, class: "btn-main")%>
        </div>
				
				<div class="supporting-section">
          <br>
          <h1>Relive and share your adventures</h1>
          <br>
          <p>Stories automatically creates a digital journal filled with only your best photos</p>
				</div>
				
				<div class="secondary-section">
				</div>
				
				<div class="discover-section">
          <br>
          <h1>Discover Stories</h1>
          <br>
          <br>
             <%= link_to("Learn More", about_path, class: "btn-main")%>
				</div>
    		
				

app/views/pages/thanks.html.erb
<div class="thanks-div">
<h1>
Thanks will be in touch.
</h1>
</div>

app/views/signups/new.html.erb
<div class="the-form">
<h1>Get the Latest Updates from Stories</h1>
<%= form_for(@signup) do |f| %>  
  <div class="field"> 
    <%= f.label :firstname %><br>
    <%= f.text_area :firstname %> <br>
    <%= f.label :email %><br>
    <%= f.text_area :email %> 
  </div> 
  <div class="actions"> 
    <%= f.submit "Join" %> 
  </div> 
<% end %>
</div>